package main

import (
	"fmt"
)

// PrintHelp prints the utility's usage instructions, flag descriptions, and default behaviors with ansi colors.
func PrintHelp() {
	fmt.Println(ColorCyan + "==========================================================" + ColorReset)
	fmt.Println(ColorCyan + ColorBold + "       DigitalPersona PM File Copier (Go Version) v" + Version + ColorReset)
	fmt.Println(ColorCyan + ColorBold + "                      HELP & USAGE" + ColorReset)
	fmt.Println(ColorCyan + "==========================================================" + ColorReset)
	fmt.Println(ColorBold + "Usage:" + ColorReset)
	fmt.Println("  copy-pm-files.exe [flags]")
	fmt.Println()
	fmt.Println(ColorBold + "Flags:" + ColorReset)
	fmt.Println("  " + ColorCyan + "-config" + ColorReset + " <path>")
	fmt.Println("        Path to the configuration JSON file.")
	fmt.Println("        [Default]: \"config.json\" (looks in current working directory and next to the executable).")
	fmt.Println()
	fmt.Println("  " + ColorCyan + "-release" + ColorReset)
	fmt.Println("        Targets Release compiled files instead of Debug compiled files.")
	fmt.Println("        [Default]: false (targets Debug compiled files).")
	fmt.Println()
	fmt.Println("  " + ColorCyan + "-source" + ColorReset + " <paths>")
	fmt.Println("        Comma-separated list of custom source directories to copy files from.")
	fmt.Println("        [Note 1]: If any paths contain spaces, you MUST enclose the entire")
	fmt.Println("        comma-separated list in double quotes, for example:")
	fmt.Println("          -source \"C:/Folder With Spaces/Win32,C:/Other Folder/x64\"")
	fmt.Println()
	fmt.Println("        [Note 2]: If a path contains literal commas, escape them with a backslash (\\,):")
	fmt.Println("          -source \"C:/Folder\\, With Comma/Win32,C:/NormalFolder/x64\"")
	fmt.Println("        Specifying this option bypasses both the configuration file and Windows Registry.")
	fmt.Println("        [Default]: Unspecified (resolves sources from configuration file or registry fallback).")
	fmt.Println()
	fmt.Println("  " + ColorCyan + "-set" + ColorReset + " <name>")
	fmt.Println("        Designate a specific configuration set from config.json to execute (and only this one)")
	fmt.Println("        regardless of whether its 'isActive' attribute is set to true or false.")
	fmt.Println("        [Default]: Unspecified (processes all sets with 'isActive' set to true).")
	fmt.Println()
	fmt.Println("  " + ColorCyan + "-force" + ColorReset)
	fmt.Println("        Force copy all targeted files regardless of their timestamps.")
	fmt.Println("        [Default]: false (uses 'copy if newer' timestamp comparison).")
	fmt.Println()

	// Print Default Behaviors & Fallbacks section in Dim/Gray (reduced brightness)
	fmt.Println(ColorDim + "Default Behaviors & Fallbacks:")
	fmt.Println("  1. Configuration Resolution Flow:")
	fmt.Println("     - If '-source' is specified, those folders are processed immediately.")
	fmt.Println("     - Else, the tool tries to load the specified config JSON file (defaults to \"config.json\").")
	fmt.Println("     - If the config file cannot be loaded or contains no paths, the tool automatically falls back")
	fmt.Println("       to reading paths from the Windows Registry key:")
	fmt.Println("         HKEY_CURRENT_USER\\SOFTWARE\\SergeiMenchenin\\CopyPmFilesToBin")
	fmt.Println("     - If no paths are resolved via any method, the program outputs an error and exits.")
	fmt.Println()
	fmt.Println("  2. Destination Path Defaults:")
	fmt.Println("     - If destination paths ('win32' or 'x64' keys under 'dp.paths.dst' in the config file)")
	fmt.Println("       are empty, omitted, or null, they automatically fallback to default system-wide paths:")
	fmt.Println("       - Win32 files copy to:")
	fmt.Println("           %ProgramFiles(x86)%\\DigitalPersona\\Bin (typically C:\\Program Files (x86)\\DigitalPersona\\Bin)")
	fmt.Println("       - x64 files copy to:")
	fmt.Println("           %ProgramFiles%\\DigitalPersona\\Bin (typically C:\\Program Files\\DigitalPersona\\Bin)")
	fmt.Println("     - If custom paths are specified, those are used instead (supporting forward/backward slashes).")
	fmt.Println()
	fmt.Println("  3. Graceful DPAgent Termination:")
	fmt.Println("     - Before copying, the tool automatically searches for running 'DPAgent.exe' processes.")
	fmt.Println("     - It gracefully posts a WM_CLOSE message to its window and waits up to 10 seconds for it to close.")
	fmt.Println("     - If DPAgent is not running, or exits successfully, copying begins immediately." + ColorReset)
	fmt.Println()
	fmt.Println(ColorCyan + "==========================================================" + ColorReset)
}
