package main

import (
	"fmt"
)

// PrintHelp prints the utility's usage instructions, flag descriptions, and default behaviors.
func PrintHelp() {
	fmt.Println("==========================================================")
	fmt.Println("       DigitalPersona PM File Copier (Go Version)")
	fmt.Println("                      HELP & USAGE")
	fmt.Println("==========================================================")
	fmt.Println("Usage:")
	fmt.Println("  copy-pm-files.exe [flags]")
	fmt.Println()
	fmt.Println("Flags:")
	fmt.Println("  -config <path>")
	fmt.Println("        Path to the configuration JSON file.")
	fmt.Println("        [Default]: \"config.json\" (looks in current working directory and next to the executable).")
	fmt.Println()
	fmt.Println("  -release")
	fmt.Println("        Targets Release compiled files instead of Debug compiled files.")
	fmt.Println("        [Default]: false (targets Debug compiled files).")
	fmt.Println()
	fmt.Println("  -source <paths>")
	fmt.Println("        Comma-separated list of custom source directories to copy files from.")
	fmt.Println("        Specifying this option bypasses both the configuration file and Windows Registry.")
	fmt.Println("        [Default]: Unspecified (resolves sources from configuration file or registry fallback).")
	fmt.Println()
	fmt.Println("Default Behaviors & Fallbacks:")
	fmt.Println("  1. Configuration Resolution Flow:")
	fmt.Println("     - If '-source' is specified, those folders are processed immediately.")
	fmt.Println("     - Else, the tool tries to load the specified config JSON file (defaults to \"config.json\").")
	fmt.Println("     - If the config file cannot be loaded or contains no paths, the tool automatically falls back")
	fmt.Println("       to reading paths from the Windows Registry key:")
	fmt.Println("         HKEY_CURRENT_USER\\SOFTWARE\\SergeiMenchenin\\CopyPmFilesToBin")
	fmt.Println("     - If no paths are resolved via any method, the program outputs an error and exits.")
	fmt.Println()
	fmt.Println("  2. Destination Path Defaults:")
	fmt.Println("     - If destination paths ('win32' or 'x64' keys under 'dp.paths.dst' in the config file)")
	fmt.Println("       are empty, omitted, or null, they automatically fallback to default system-wide paths:")
	fmt.Println("       - Win32 files copy to:")
	fmt.Println("           %ProgramFiles(x86)%\\DigitalPersona\\Bin (typically C:\\Program Files (x86)\\DigitalPersona\\Bin)")
	fmt.Println("       - x64 files copy to:")
	fmt.Println("           %ProgramFiles%\\DigitalPersona\\Bin (typically C:\\Program Files\\DigitalPersona\\Bin)")
	fmt.Println("     - If custom paths are specified, those are used instead (supporting forward/backward slashes).")
	fmt.Println()
	fmt.Println("  3. Graceful DPAgent Termination:")
	fmt.Println("     - Before copying, the tool automatically searches for running 'DPAgent.exe' processes.")
	fmt.Println("     - It gracefully posts a WM_CLOSE message to its window and waits up to 10 seconds for it to close.")
	fmt.Println("     - If DPAgent is not running, or exits successfully, copying begins immediately.")
	fmt.Println("==========================================================")
}
